<?php

/**
 * Class to use PHPDocX within a namespace
 *
 * @category   Phpdocx
 * @package    factory
 * @copyright  Copyright (c) Narcea Producciones Multimedia S.L.
 *             (http://www.2mdc.com)
 * @license    http://www.phpdocx.com/wp-content/themes/lightword/pro_license.php
 * @version    2014.04.09
 * @link       http://www.phpdocx.com
 */
require_once dirname(__FILE__) . '/CreateDocx.inc';

class Phpdocx_Phpdocx extends CreateDocx
{
    
}
